### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by marttt** [manolomartinez/greg#2]
Hi,
I'm on Debian and Python 2.7. After doing `sudo python setup.py install` and trying to run greg, I got this error:

```
File "/usr/local/bin/greg", line 19, in <module>
from greg.gregparser import main 
ImportError: No module named greg.gregparser
```

I tried running greg.py from the /greg/greg folder, but that gave another error:

```
File "greg.py", line 185
    print (feed, end=" ")
                    ^
SyntaxError: invalid syntax
```

Also, I had to add `# coding=utf-8` to both setup.py and then to /usr/local/bin/greg. Without this, I got the following error:

```
SyntaxError: Non-ASCII character '\xc3' in file setup.py on line 8, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```

Here's my entire log:

```
mart@mart:~/downloads/greg$ sudo python setup.py install
running install
running build
running build_py
package init file 'greg/__init__.py' not found (or not a regular file)
creating build
creating build/lib.linux-i686-2.7
creating build/lib.linux-i686-2.7/greg
copying greg/gregparser.py -> build/lib.linux-i686-2.7/greg
copying greg/greg.py -> build/lib.linux-i686-2.7/greg
package init file 'greg/__init__.py' not found (or not a regular file)
running build_scripts
creating build/scripts-2.7
copying and adjusting bin/greg -> build/scripts-2.7
changing mode of build/scripts-2.7/greg from 644 to 755
running install_lib
creating /usr/local/lib/python2.7/dist-packages/greg
copying build/lib.linux-i686-2.7/greg/gregparser.py -> /usr/local/lib/python2.7/dist-packages/greg
copying build/lib.linux-i686-2.7/greg/greg.py -> /usr/local/lib/python2.7/dist-packages/greg
byte-compiling /usr/local/lib/python2.7/dist-packages/greg/gregparser.py to gregparser.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/greg/greg.py to greg.pyc
SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/greg/greg.py', 183, 25, '        print (feed, end=" ")\n'))

running install_scripts
copying build/scripts-2.7/greg -> /usr/local/bin
changing mode of /usr/local/bin/greg to 755
running install_data
copying data/greg.conf -> /etc
running install_egg_info
Writing /usr/local/lib/python2.7/dist-packages/Greg-0.1.0.egg-info

mart@mart:~/downloads/greg$ cd ~
mart@mart:~$ greg
Traceback (most recent call last):
  File "/usr/local/bin/greg", line 19, in <module>
    from greg.gregparser import main 
ImportError: No module named greg.gregparser
```

Thanks for any help!

Based on the readme, it appears to be a perfect tool for me, though. So another thanks for your effort! :)

**Comment by winny-** [comment]
Hi! It might be a good idea to include compatibility information in the README, since only on pypi are categories visible next to the readme.

**Comment by manolomartinez** [comment]
Hi, would you mind opening a new issue for this?

Anyway. that's what I hoped the "written in Python 3" was doing. Not so?

**Comment by winny-** [comment]
Oh wow, how did I miss that? Never mind, that's pretty much what I was asking for. :+:
