### ISSUE TITLE
greg does not list podcasts

### ISSUE THREAD

**Issue by rohshall** [manolomartinez/greg#52]
`
~ % cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu Xenial Xerus (development branch)"

~ % which greg
.local/bin/greg
`

`
 ~ % greg list                                            
Traceback (most recent call last):
  File ".local/bin/greg", line 9, in <module>
    load_entry_point('Greg==0.4.6', 'console_scripts', 'greg')()
  File "/home/swadnerkar/.local/lib/python3.5/site-packages/greg/gregparser.py", line 118, in main
    function(vars(args))
  File "/home/swadnerkar/.local/lib/python3.5/site-packages/greg/greg.py", line 734, in list_for_user
    session = Session(args)
  File "/home/swadnerkar/.local/lib/python3.5/site-packages/greg/greg.py", line 55, in __init__
    self.data_dir = self.retrieve_data_directory()
  File "/home/swadnerkar/.local/lib/python3.5/site-packages/greg/greg.py", line 95, in retrieve_data_directory
    config.read([config_filename_global, self.config_filename_user])
  File "/usr/lib/python3.5/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/lib/python3.5/configparser.py", line 1012, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 33: ordinal not in range(128)
`

**Comment by manolomartinez** [comment]
Hi, Id' bet this is a problem with your locale. Please post the output of `locale` and `locale -a`. Do other python programs work well? Other greg subcommands?

**Comment by rohshall** [comment]
You are right. My locale was set to POSIX and when I set it to 'en_US.UTF-8', the problem disappeared.
