### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by Joeslavins** [manolomartinez/greg#64]
Hello,

Quite often while downloading an episode i encounter the following error

````bash
Checking lineardigressions... 
Downloading Kalman Runners -- 230576907-linear-digressions-kalman-runners.mp3 
Traceback (most recent call last): 
 File "/home/username/.local/bin/greg", line 11, in <module> 
   sys.exit(main()) 
 File "/home/username/.local/lib/python3.5/site-packages/greg/parser.py", line 138, in main 
   function(vars(args)) 
 File "/home/username/.local/lib/python3.5/site-packages/greg/commands.py", line 176, in sync 
   downloaded = feed.download_entry(entry) 
 File "/home/username/.local/lib/python3.5/site-packages/greg/classes.py", line 329, in download_entry 
   aux.download_handler(self, placeholders) 
 File "/home/username/.local/lib/python3.5/site-packages/greg/aux_functions.py", line 223, in download_handler 
   urlretrieve(placeholders.link, placeholders.fullpath) 
 File "/usr/lib/python3.5/urllib/request.py", line 217, in urlretrieve 
   block = fp.read(bs) 
 File "/usr/lib/python3.5/http/client.py", line 448, in read 
   n = self.readinto(b) 
 File "/usr/lib/python3.5/http/client.py", line 488, in readinto 
   n = self.fp.readinto(b) 
 File "/usr/lib/python3.5/socket.py", line 575, in readinto 
   return self._sock.recv_into(b) 
ConnectionResetError: [Errno 104] Connection reset by peer
```

Is this an error with greg or the podcast website?

**Comment by manolomartinez** [comment]
Hello, it looks like an error with the podcast not greg, but let me know that podcast's address and I'll take a look.
M
