### ISSUE TITLE
Cant install greg with setup.py 

### ISSUE THREAD

**Issue by sddhrthrt** [manolomartinez/greg#68]
I'm trying to install using your setup.py script, but I'm not able to "import greg" after installing it. (im inside a virtualenv, I have stagger installed)

Here's my console output:

```
(greg) ✔ ~/src/personal/greg [master|✚ 1…41] 
23:04 $ ./setup.py build
running build
running build_py
package init file 'greg/__init__.py' not found (or not a regular file)
(greg) ✔ ~/src/personal/greg [master|✚ 1…41] 
23:04 $ ./setup.py install
running install
running bdist_egg
running egg_info
writing top-level names to Greg.egg-info/top_level.txt
writing entry points to Greg.egg-info/entry_points.txt
writing dependency_links to Greg.egg-info/dependency_links.txt
writing Greg.egg-info/PKG-INFO
writing requirements to Greg.egg-info/requires.txt
package init file 'greg/__init__.py' not found (or not a regular file)
reading manifest file 'Greg.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'Greg.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/greg
creating build/bdist.linux-x86_64/egg/greg/data
copying build/lib/greg/data/greg.conf -> build/bdist.linux-x86_64/egg/greg/data
copying build/lib/greg/parser.py -> build/bdist.linux-x86_64/egg/greg
copying build/lib/greg/classes.py -> build/bdist.linux-x86_64/egg/greg
copying build/lib/greg/aux_functions.py -> build/bdist.linux-x86_64/egg/greg
copying build/lib/greg/commands.py -> build/bdist.linux-x86_64/egg/greg
byte-compiling build/bdist.linux-x86_64/egg/greg/parser.py to parser.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/greg/classes.py to classes.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/greg/aux_functions.py to aux_functions.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/greg/commands.py to commands.cpython-35.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying Greg.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Greg.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Greg.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Greg.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Greg.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Greg.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/Greg-0.4.7-py3.5.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing Greg-0.4.7-py3.5.egg
Copying Greg-0.4.7-py3.5.egg to /home/thota/data/src/venvs/greg/lib/python3.5/site-packages
Adding Greg 0.4.7 to easy-install.pth file
Installing greg script to /home/thota/src/venvs/greg/bin

Installed /home/thota/data/src/venvs/greg/lib/python3.5/site-packages/Greg-0.4.7-py3.5.egg
Processing dependencies for Greg==0.4.7
Searching for feedparser==5.2.1
Best match: feedparser 5.2.1
Processing feedparser-5.2.1-py3.5.egg
feedparser 5.2.1 is already the active version in easy-install.pth

Using /home/thota/data/src/venvs/greg/lib/python3.5/site-packages/feedparser-5.2.1-py3.5.egg
Finished processing dependencies for Greg==0.4.7
```

And now, if I try running greg:
```
(greg) ✔ ~/src/personal/greg [master|✚ 1…41] 
23:04 $ greg
Traceback (most recent call last):
  File "/home/thota/src/venvs/greg/bin/greg", line 11, in <module>
    load_entry_point('Greg==0.4.7', 'console_scripts', 'greg')()
  File "/home/thota/src/venvs/greg/lib/python3.5/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/thota/src/venvs/greg/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/home/thota/src/venvs/greg/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/home/thota/src/venvs/greg/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named 'greg'
```

I cant import greg from a python terminal too.

I'm using python3.

**Comment by s-nt-s** [comment]
I have the same problem:

```$ python3 ./setup.py install --user
running install
running bdist_egg
running egg_info
writing Greg.egg-info/PKG-INFO
writing top-level names to Greg.egg-info/top_level.txt
writing entry points to Greg.egg-info/entry_points.txt
writing requirements to Greg.egg-info/requires.txt
writing dependency_links to Greg.egg-info/dependency_links.txt
package init file 'greg/__init__.py' not found (or not a regular file)
reading manifest file 'Greg.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'Greg.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/greg
copying build/lib/greg/classes.py -> build/bdist.linux-x86_64/egg/greg
copying build/lib/greg/aux_functions.py -> build/bdist.linux-x86_64/egg/greg
copying build/lib/greg/parser.py -> build/bdist.linux-x86_64/egg/greg
copying build/lib/greg/commands.py -> build/bdist.linux-x86_64/egg/greg
creating build/bdist.linux-x86_64/egg/greg/data
copying build/lib/greg/data/greg.conf -> build/bdist.linux-x86_64/egg/greg/data
byte-compiling build/bdist.linux-x86_64/egg/greg/classes.py to classes.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/greg/aux_functions.py to aux_functions.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/greg/parser.py to parser.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/greg/commands.py to commands.cpython-34.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying Greg.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Greg.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Greg.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Greg.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Greg.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Greg.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/Greg-0.4.7-py3.4.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing Greg-0.4.7-py3.4.egg
Removing /home/santos/.local/lib/python3.4/site-packages/Greg-0.4.7-py3.4.egg
Copying Greg-0.4.7-py3.4.egg to /home/santos/.local/lib/python3.4/site-packages
Greg 0.4.7 is already the active version in easy-install.pth
Installing greg script to /home/santos/.local/bin

Installed /home/santos/.local/lib/python3.4/site-packages/Greg-0.4.7-py3.4.egg
Processing dependencies for Greg==0.4.7
Searching for feedparser==5.2.1
Best match: feedparser 5.2.1
Processing feedparser-5.2.1-py3.4.egg
feedparser 5.2.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.4/dist-packages/feedparser-5.2.1-py3.4.egg
Finished processing dependencies for Greg==0.4.7
```

```$ greg info
Traceback (most recent call last):
  File "/home/user/.local/bin/greg", line 9, in <module>
    load_entry_point('Greg==0.4.7', 'console_scripts', 'greg')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named 'greg'
```

**Comment by manolomartinez** [comment]
Just to make sure, if you install it via pip:  `pip install git+file:///path/to/greg`, does it work?

**Comment by sddhrthrt** [comment]
Let me give that a try.
